//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.26 at 03:48:50 PM IST 
//


package com.springsoapexamples.spring_soap_examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="empID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="empSalary" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {
    "userName",
    "empID",
    "empSalary"
})
public class User {

    @XmlElement(required = true)
    protected String userName;
    protected int empID;
    protected double empSalary;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the empID property.
     * 
     */
    public int getEmpID() {
        return empID;
    }

    /**
     * Sets the value of the empID property.
     * 
     */
    public void setEmpID(int value) {
        this.empID = value;
    }

    /**
     * Gets the value of the empSalary property.
     * 
     */
    public double getEmpSalary() {
        return empSalary;
    }

    /**
     * Sets the value of the empSalary property.
     * 
     */
    public void setEmpSalary(double value) {
        this.empSalary = value;
    }

}
